[package]
name = "uciinspector"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "inspector"
crate-type = ["cdylib"]


[dependencies]
cozy-chess = "0.3.3"
